name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-integrity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
        with:
          node-version: 18
    
    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build Docs
      run: npm run build

    - name: Build container image
      run: docker build .
